# -*- coding: utf-8 -*-
"""prompting_qwen_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_kXv15WF_fgarJPV_s4GeaFNlvO3BbQ

###1. Загрузим легкую модель Qwen и на простом промте измерим качество.         
Полученный результат будем считать за baseline, который будем пытаться перебить с помощью   
  a) Улучшения промта (chain of thoughts, детализация и тд).  
  b) Более мощной модели по числу параметров.  
  с) Другой модели.  
  d) Перехода в fine-tuning.  


###2. Специфика данных:   
Эссе оценивается по 4-м критериям, итоговая оценка это просто среднее из них. Поэтому мы хотим от модели попадания в каждый из критериев, помимо общей оценки.

###3. Выбранные метрики качества:  
**MAE** - покажет в баллах на сколько ошибаемся в предсказании, что очень наглядно. Будем в идеале стремиться к тому, чтобы модель ошибалась менее, чем на 0.5 балла  
**RMSE** - учитываем выбросы. Считаем, что дать сильно неправильную оценку за эссе это критически плохо   
**MBE** - модель в реднем завышает или занижает предсказания? Будем стремиться к тому, чтобы модель минимально завышала/занижала оценки.

###4. Формирование пайплайна
Этот же код будем использовать при тесте других моделей/ промтов
"""

# !pip install -q transformers accelerate bitsandbytes pandas datasets torch -- расскомментировать если такой штуки еще не установлено

import torch
print(f"GPU доступен: {torch.cuda.is_available()}")
print(f"Устройство: {torch.cuda.get_device_name(0)}")
print(f"Память: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# Это наш выбранный датасет с каггла, в нем данные сразу разбиты на тест и трейн

!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d xuanhuynh233/ielts-dataset
!unzip ielts-dataset.zip

csv_path = 'train_final.csv'
df = pd.read_csv(csv_path)

print(df.head())
print(f"Размер датасета: {len(df)} строк.")

# Удалим строки, где 'essay' или 'band' отсутствуют,
# или 'band' не является числом.

initial_len = len(df)
df = df.dropna(subset=['essay', 'band'])
df = df[pd.to_numeric(df['band'], errors='coerce').notna()]
df['band'] = df['band'].astype(float) # Убедимся, что band это float
print(f"\nУдалено {initial_len - len(df)} строк с отсутствующими или некорректными 'essay'/'band'.")
print(f"Осталось {len(df)} строк после очистки.")

df

"""## загрузка QWEN"""

# !pip uninstall -y bitsandbytes
# !pip install bitsandbytes>=0.46.1

# Перезапустите сеанс

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

# Конфигурация 4-bit квантизации - чтобы быстро скачать и чтобы быстро работало (для пробы пера)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model_name = "Qwen/Qwen2.5-3B-Instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

"""Легкая qwen с квантизацией скачивалась 2 минуты - норм"""

# сразу все импорты
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error, mean_absolute_error
from scipy.stats import spearmanr
import re
from tqdm import tqdm
import torch

# базовый промт
def create_ielts_prompt(essay_to_grade, example_essays):

    prompt = """You are an expert IELTS Writing Task 2 examiner. Grade essays using IELTS band descriptors (0-9, step 0.5).

IELTS CRITERIA (each 0-9):
1. TR (Task Response): How well the essay addresses the task, presents ideas, and supports arguments
2. CC (Coherence & Cohesion): Organization, paragraph structure, and linking devices
3. LR (Lexical Resource): Vocabulary range, accuracy, and appropriateness
4. GRA (Grammatical Range & Accuracy): Grammar variety, accuracy, and complexity

IMPORTANT:
- Use only 0.5 increments (e.g., 6.0, 6.5, 7.0)
- Overall Band = Average of all 4 criteria
- Provide realistic scores based on IELTS standards

Here are graded examples:

"""

    for i, example in enumerate(example_essays, 1):
        prompt += f"""Example {i}:
Essay: "{example['essay']}..."
TR_Band: {example['TR_Band']}
CC_Band: {example['CC_Band']}
LR_Band: {example['LR_Band']}
GRA_Band: {example['GRA_Band']}
Overall_Band: {example['Overall_Band']}
---

"""

    prompt += f"""Now, grade this essay following IELTS standards:

Essay: "{essay_to_grade}"

Provide your evaluation in this EXACT format:
TR_Band: X.X
CC_Band: X.X
LR_Band: X.X
GRA_Band: X.X
Overall_Band: X.X
Explanation: [Brief justification for each criterion]
"""

    return prompt

# получим все оценки из ответа модели, чтобы считать по ним метрики качества

def extract_ielts_scores(response):

    # Извлечем 5 оценок {'TR': float, 'CC': float, 'LR': float, 'GRA': float, 'Overall': float}

    scores = {}

    patterns = {
        'TR': r'TR[_\s]*Band:\s*(\d+(?:\.\d)?)',
        'CC': r'CC[_\s]*Band:\s*(\d+(?:\.\d)?)',
        'LR': r'LR[_\s]*Band:\s*(\d+(?:\.\d)?)',
        'GRA': r'GRA[_\s]*Band:\s*(\d+(?:\.\d)?)',
        'Overall': r'Overall[_\s]*Band:\s*(\d+(?:\.\d)?)'
    }

    for criterion, pattern in patterns.items():
        match = re.search(pattern, response, re.IGNORECASE)
        if match:
            score = float(match.group(1))
            score = round(score * 2) / 2
            scores[criterion] = min(max(score, 0), 9)
        else:
            scores[criterion] = None

    if scores['Overall'] is None and all(scores[k] is not None for k in ['TR', 'CC', 'LR', 'GRA']):
        avg = np.mean([scores['TR'], scores['CC'], scores['LR'], scores['GRA']])
        scores['Overall'] = round(avg * 2) / 2

    return scores

# функция оценки эссе по нашему промту
def grade_ielts_essay(essay, example_essays, model, tokenizer, max_tokens=600):


    prompt = create_ielts_prompt(essay, example_essays)
    # задаем роль
    messages = [
        {"role": "system", "content": "You are an expert IELTS Writing examiner with years of experience."},
        {"role": "user", "content": prompt}
    ]


    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer([text], return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=0.2,  # Очень низкая для стабильности, была 0.3, выдавала разницу в качестве в 1 единцу MAE
            top_p=0.9,
            do_sample=True,
            repetition_penalty=1.1
        )

    response = tokenizer.decode(
        outputs[0][inputs['input_ids'].shape[1]:],
        skip_special_tokens=True
    )

    return response

# sample_size = 100  # отрабатывает час - больше не хочется повторять этот экспириенс
sample_size = 50
test_df = df.sample(sample_size, random_state=42).copy()

# будем давать 5 примеров оценненых эссе внутри промта
examples = df[~df.index.isin(test_df.index)].sample(5).to_dict('records')

predictions = {
    'TR': [],
    'CC': [],
    'LR': [],
    'GRA': [],
    'Overall': []
}
explanations = []

print(f"Оценка {sample_size} IELTS эссе...")

for idx, row in tqdm(test_df.iterrows(), total=len(test_df)):
    try:
        # Генерация оценки моделью по промту
        response = grade_ielts_essay(
            row['essay'],
            examples,
            model,
            tokenizer,
            max_tokens=600
        )

        # Извлечение оценок из ответа модели
        scores = extract_ielts_scores(response)

        for criterion in ['TR', 'CC', 'LR', 'GRA', 'Overall']:
            predictions[criterion].append(scores[criterion])

        explanations.append(response)

    except Exception as e:
        print(f"\n Ошибка на эссе {idx}: {e}")
        for criterion in predictions.keys():
            predictions[criterion].append(None)
        explanations.append("")

# Добавляем результаты в датафрейм
for criterion in ['TR', 'CC', 'LR', 'GRA', 'Overall']:
    test_df[f'pred_{criterion}'] = predictions[criterion]

test_df['explanation'] = explanations

print("\n Оценка завершена!")

"""#### На каждое эссе тратится около минуты, в будущем хотелось бы ускорить время работы
Тотал - 41 минута на 50 эссе
"""

# оцениваем качество модели

def calculate_ielts_metrics(actual, predicted):

    mask = ~(pd.isna(actual) | pd.isna(predicted))
    actual = np.array(actual)[mask]
    predicted = np.array(predicted)[mask]

    if len(actual) == 0:
        return None

    # MAE
    mae = mean_absolute_error(actual, predicted)

    # RMSE
    rmse = np.sqrt(mean_squared_error(actual, predicted))

    # MBE чтобы понимать занижение/завышение оценок
    mbe = np.mean(predicted - actual)

    # Корреляция Спирмена
    correlation, _ = spearmanr(actual, predicted)

    # Точность
    acc_05 = np.mean(np.abs(predicted - actual) <= 0.5)
    acc_10 = np.mean(np.abs(predicted - actual) <= 1.0)

    # Процент точных совпадений (особенно важно для 0.5 шага)
    exact_match = np.mean(predicted == actual)

    # QWK
    from sklearn.metrics import cohen_kappa_score
    qwk = cohen_kappa_score(
        (actual * 2).astype(int),  # Переводим в целые (умножаем на 2)
        (predicted * 2).astype(int),
        weights='quadratic'
    )

    return {
        'MAE': mae,
        'RMSE': rmse,
        'MBE': mbe,
        'Correlation': correlation,
        'QWK': qwk,
        'Accuracy_±0.5': acc_05,
        'Accuracy_±1.0': acc_10,
        'Exact_Match': exact_match,
        'n_samples': len(actual)
    }


print("метрики качества")

criteria_mapping = {
    'TR': 'TR_Band',
    'CC': 'CC_Band',
    'LR': 'LR_Band',
    'GRA': 'GRA_Band',
    'Overall': 'Overall_Band'
}

all_metrics = {}

for criterion, actual_col in criteria_mapping.items():

    print(f" {criterion} ({actual_col})")
    actual = test_df[actual_col]
    predicted = test_df[f'pred_{criterion}']

    metrics = calculate_ielts_metrics(actual, predicted)

    if metrics:
        all_metrics[criterion] = metrics

        print(f"MAE:              {metrics['MAE']:.3f} bands")
        print(f"RMSE:             {metrics['RMSE']:.3f} bands")
        print(f"MBE:              {metrics['MBE']:+.3f} bands {'(завышение)' if metrics['MBE'] > 0 else '(занижение)' if metrics['MBE'] < 0 else '(нет смещения)'}")
        print(f"Корреляция:       {metrics['Correlation']:.3f}")
        print(f"QWK:              {metrics['QWK']:.3f}")
        print(f"Точность ±0.5:    {metrics['Accuracy_±0.5']:.1%}")
        print(f"Точность ±1.0:    {metrics['Accuracy_±1.0']:.1%}")
        print(f"Точное совпадение: {metrics['Exact_Match']:.1%}")
        print(f"Обработано:       {metrics['n_samples']} эссе")
    else:
        print(" Недостаточно данных для расчета метрик")

metrics_df = pd.DataFrame(all_metrics).T
metrics_df = metrics_df.round(3)
print(metrics_df[['MAE', 'RMSE', 'MBE', 'Correlation', 'QWK']])

"""## Промежуточные выводы:

- Получили неплохое качество по MAE - по промежуточным оценкам и итоговым отклонение не больше 1,1 балла из 9
- Модель переоценивает максимум на 0,15 балла, в среднем недооценивает на 0,27 балла
- На метрике согласия QWK получили какой-то бред - модель работает практичсеки случайно 🤟

## Конец пайплайна
1) подача промта
2) работа модели на основе этого промта на случайной подвыборке из тестового датасета
3) оценка качества модели

Дальше подробнее посмотрим на вывод модели
"""

# выведем граничные метрики качества по всем оценкам
for criterion in criteria_names:
    actual = test_df[criteria_mapping[criterion]]
    predicted = test_df[f'pred_{criterion}']

    mask = actual.notna() & predicted.notna()
    errors = (predicted[mask] - actual[mask]).abs()

    print(f"\n{criterion}:")
    print(f"  Макс. ошибка: {errors.max():.1f} bands")
    print(f"  Мин. ошибка:  {errors.min():.1f} bands")
    print(f"  Медиана:      {errors.median():.2f} bands")
    print(f"  95 перцентиль: {errors.quantile(0.95):.2f} bands")

#  вытащим примеры работы модели
valid_overall = test_df.dropna(subset=['pred_Overall'])
valid_overall['error'] = abs(valid_overall['Overall_Band'] - valid_overall['pred_Overall'])


print("\n лучшие варианты")
best = valid_overall.nsmallest(3, 'error')

for idx in best.index:
    row = test_df.loc[idx]

    print(f"Эссе: {row['essay']}...")
    print(f"\nИстинные оценки:")
    print(f"  TR: {row['TR_Band']:.1f}, CC: {row['CC_Band']:.1f}, LR: {row['LR_Band']:.1f}, GRA: {row['GRA_Band']:.1f}")
    print(f"  Overall: {row['Overall_Band']:.1f}")
    print(f"\nПредсказанные оценки:")
    print(f"  TR: {row['pred_TR']:.1f}, CC: {row['pred_CC']:.1f}, LR: {row['pred_LR']:.1f}, GRA: {row['pred_GRA']:.1f}")
    print(f"  Overall: {row['pred_Overall']:.1f}")
    print(f"\n Ошибка Overall: {row['error']:.2f} bands")


print("\n\n худшие варианты")
worst = valid_overall.nlargest(3, 'error')

for idx in worst.index:
    row = test_df.loc[idx]
    print(f"Эссе: {row['essay']}...")
    print(f"\nИстинные оценки:")
    print(f"  TR: {row['TR_Band']:.1f}, CC: {row['CC_Band']:.1f}, LR: {row['LR_Band']:.1f}, GRA: {row['GRA_Band']:.1f}")
    print(f"  Overall: {row['Overall_Band']:.1f}")
    print(f"\nПредсказанные оценки:")
    print(f"  TR: {row['pred_TR']:.1f}, CC: {row['pred_CC']:.1f}, LR: {row['pred_LR']:.1f}, GRA: {row['pred_GRA']:.1f}")
    print(f"  Overall: {row['pred_Overall']:.1f}")
    print(f"\n Ошибка Overall: {row['error']:.2f} bands")


test_df.to_csv('ielts_predictions.csv', index=False)
metrics_df.to_csv('ielts_metrics.csv')

"""## Итоги:
Неплохо решаем задачу предсказывания оценки с помощью промптинга, дальше псмотрим получится ли улучшить качество и сможем ли мы как-то оценить еще и фидбек от модели?
"""