name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: salarion-witch/pzad_ielts
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: streamlit
          subdirectory: space
